### ISSUE TITLE
ERROR TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by shivark** [ngx-config/fs-loader#1]
I'm getting the following error in browser console:

zone.js:655 Unhandled Promise rejection: __webpack_require__.i(...) is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: __webpack_require__.i(...) is not a function
    at ConfigFsLoader.loadSettings (config.fs-loader.js:8)
    at ConfigService.init (config.service.js:10)
    at Array.res (index.js:13)
    at ApplicationInitStatus.runInitializers (core.es5.js:2807)
    at core.es5.js:4505
    at _callAndReportToErrorHandler (core.es5.js:4405)
    at core.es5.js:4503
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.es5.js:3890)
    at ZoneDelegate.invoke (zone.js:390) TypeError: __webpack_require__.i(...) is not a function
    at ConfigFsLoader.loadSettings (http://localhost:5000/dist/main-browser.js:79940:114)
    at ConfigService.init (http://localhost:5000/dist/main-browser.js:29607:28)
    at Array.res (http://localhost:5000/dist/main-browser.js:32828:43)
    at ApplicationInitStatus.runInitializers (http://localhost:5000/dist/main-browser.js:3774:67)
    at http://localhost:5000/dist/main-browser.js:5472:28
    at _callAndReportToErrorHandler (http://localhost:5000/dist/main-browser.js:5372:39)
    at http://localhost:5000/dist/main-browser.js:5470:20
    at ZoneDelegate.invoke (http://localhost:5000/dist/main-browser.js:88485:26)
    at Object.onInvoke (http://localhost:5000/dist/main-browser.js:4857:33)
    at ZoneDelegate.invoke (http://localhost:5000/dist/main-browser.js:88484:32)

**Comment by fabis94** [comment]
Any news regarding this?

**Comment by shivark** [comment]
@fabis94 nope sorry, I gave up using this. I'm using old version of ngx-config that allow me to make Http call to a json file stores locally.

**Comment by fulls1z3** [comment]
@shivark @fabis94 sorry for late answer but I want to ask if you've changed the `node` section of webpack config (*for the browser bundle*) to `empty` the `fs`?

If not, I suggest you adding the following part to your webpack config:
```javascript
node: {
  fs: 'empty'
}
```

You can check this file in order to see how that webpack config should be: https://github.com/fulls1z3/angular-webpack-config/blob/master/src/webpack.common.js#L446

**Comment by shivark** [comment]
@fulls1z3 Thanks for the reply, I will try it out. 
I recommend to add this in the package configuration description section.

**Comment by fulls1z3** [comment]
@shivark no problem, just try it out and let me know about the results. If works (*highly probable it will work*), I'll include this information at the `README`.

Also thank you really much for pointing out this issue, and I'll be glad if the solution works for you 👍

**Comment by shivark** [comment]
I'm having the same issue with another project that is generated with CLI so I don't have Webpack config file. Where should I add it?
My application is Angular 4 and cli 1.0.2
